n=int(input())
str1=list(input())
h=int(str1.count('h') // 2)
a=int(str1.count('a') // 2)
k=int(str1.count('k'))
e=int(str1.count('e') // 2)
c=int(str1.count('c'))
r=int(str1.count('r') // 2)
t=int(str1.count('t'))
print(min(h,a,e,r,t,k,c))